apiVersion: v1
kind: Pod
metadata:
  name: bm-tester-rx-noise
  annotations:
    cmk.intel.com/mutate: "true" # accepted values to trigger mutation: "true", "True", "1"
    ## Multi Interface setting part - start
    v1.multus-cni.io/default-network: default/10-contiv-vpp
spec:
  tolerations:
  - key: "cmk"
    operator: Exists
  containers:
  - name: bm-tester-rx-noise
    image: bm-pg:5000/bm-tester:1.0
    command:
    - "/bin/bash"
    - "-c"
    args:
    - "/opt/bin/cmk isolate --conf-dir=/etc/cmk --socket-id=0 --pool=infra stress-ng -- --cpu 2 --io 2 --vm 2 --vm-bytes 128M --fork 2 --timeout 600s"
    resources:
      requests:
        cmk.intel.com/exclusive-cores: 1
        hugepages-2Mi: 512Mi
        memory: 512Mi
      limits:
        cmk.intel.com/exclusive-cores: 1
        hugepages-2Mi: 512Mi
        memory: 512Mi      
    securityContext:
      privileged: true
    ###  #capabilities:
    ###  #   add:
    ###  #     - ALL
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: bm-wk
