apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 10-contiv-vpp
spec: 
  config: '{
    "name": "10-contiv-vpp",
    "cniVersion": "0.3.1",
    "plugins": [
      {
        "type": "contiv-cni",
        "grpcServer": "/var/run/contiv/cni.sock",
        "logFile": "/var/run/contiv/cni.log"
      },
      {
        "type": "portmap",
        "capabilities": {
            "portMappings": true
        },
        "externalSetMarkChain": "KUBE-MARK-MASQ"
      }
    ]
  }'
