apiVersion: v1
kind: Pod
metadata:
  name: samplepod-3
  annotations:
    k8s.v1.cni.cncf.io/networks: ovs-conf,ovs-net-2
spec:
  tolerations:
  - key: "cmk"
    operator: Exists
  containers:
  - name: samplepod
    image: wjstk16/micro:1.0
  nodeSelector:
    hostname: bm-wk
