apiVersion: v1
kind: Pod
metadata:
  name: vnf-2
  annotations:
    ## Multi Interface setting part - start
    #v1.multus-cni.io/default-network: default/10-contiv-vpp
    #contivpp.io/custom-if: tap1/tap/bm-pg-vpp2-l3
    #k8s.v1.cni.cncf.io/networks: '[
    #   {"name": "10-calico", "namespace": "default"}
    #]'
    #k8s.v1.cni.cncf.io/networks: '[
    #   {"name": "10-calico", "namespace": "default", "interface": "eth1", "ips": "192.168.41.90"}
    #]'
    ## Multi Interface setting part - end
spec:
  tolerations:
  - key: "cmk"
    operator: Exists
  containers:
  - name: vnf-2
    image: bm-pg:5000/icn-dtn-base-0.6.5:1.0
    securityContext:
      privileged: true
    command: ["/bin/sh", "-c", "sleep 1d;"]
    resources:
      limits:
        hugepages-2Mi: 512Mi
        memory: 512Mi
  nodeSelector:
    kubernetes.io/hostname: bm-wk
